/**
 * Shared types for AI diagram generation (E1 Phase 5.3, issue #537).
 * Used by both the Electron main process (electron/ai/*) and the renderer
 * (src/utils/aiDiagramBuilder.ts, src/hooks/useAiGeneration.ts) — the
 * intermediate JSON contract between the LLM provider and the canvas.
 */

export type AiProviderId = 'openai-compatible' | 'anthropic';

export interface AiProviderStatus {
  provider: AiProviderId;
  configured: boolean;
}

/**
 * Serializable projection of an Activity, sent from renderer to main so the
 * system prompt and the semantic validation layer can be built without the
 * main process depending on renderer-only activity state.
 */
export interface AiActivitySnapshot {
  id: string;
  name: string;
  category: string;
  description: string;
  params: Array<{
    name: string;
    required: boolean;
    hasDefault: boolean;
  }>;
}

/**
 * Structural block types the AI may emit. Mirrors BlockType from
 * src/types/blocks.ts minus 'parallel' (generator.ts unconditionally rejects
 * parallel-graph codegen) and 'sub-diagram-call' (requires referencing an
 * existing sub-diagram by id — out of MVP scope, see technical-debt).
 */
export const AI_BLOCK_TYPES = [
  'start',
  'end',
  'if',
  'switch',
  'while',
  'for-each',
  'retry-scope',
  'try-catch',
  'throw',
  'assign',
  'activity',
] as const;

export type AiBlockType = (typeof AI_BLOCK_TYPES)[number];

export interface AiDiagramNode {
  id: string;
  blockType: AiBlockType;
  label: string;
  /** Required when blockType === 'activity'; must match an id from the activities snapshot. */
  activityId?: string;
  /** if / while */
  condition?: string;
  /** switch */
  expression?: string;
  /** throw */
  message?: string;
  /** assign */
  variableName?: string;
  /** assign */
  variableExpression?: string;
  /** for-each */
  itemVariable?: string;
  /** for-each */
  collection?: string;
  /** switch */
  cases?: Array<{ value: string; label: string }>;
}

export interface AiDiagramEdge {
  from: string;
  to: string;
  /** Port id, e.g. "true"/"false" (if), "case-1"/"default" (switch), "error"/"finally" (try-catch). */
  handle?: string;
}

export interface AiDiagramJson {
  nodes: AiDiagramNode[];
  edges: AiDiagramEdge[];
}

export interface AiGenerateDiagramRequest {
  /** Generated by the renderer (crypto.randomUUID()); lets ai:cancelGenerate abort the matching in-flight request. */
  requestId: string;
  providerId: AiProviderId;
  prompt: string;
  activities: AiActivitySnapshot[];
}

export interface AiGenerateDiagramResult {
  success: boolean;
  diagram?: AiDiagramJson;
  /**
   * Diagnostic-only: raw validator/provider error text. Never render directly
   * in the UI (same i18n rule as mermaidImporter.ts warnings — see ADR-003.2);
   * show a localized generic message instead.
   */
  errors?: string[];
  rawText?: string;
  attempts: number;
}

export interface AiSetProviderKeyRequest {
  provider: AiProviderId;
  apiKey: string;
  baseUrl?: string;
  model?: string;
}

export interface AiTestProviderResult {
  ok: boolean;
  error?: string;
}
