/**
 * Shared types for AI diagram generation (E1 Phase 5.3, issue #537).
 * Used by both the Electron main process (electron/ai/*) and the renderer
 * (src/utils/aiDiagramBuilder.ts, src/hooks/useAiGeneration.ts) — the
 * intermediate JSON contract between the LLM provider and the canvas.
 */

export type AiProviderId = 'openai-compatible' | 'anthropic' | 'ollama' | 'groq' | 'gemini' | 'openrouter' | 'mistral' | 'nvidia-nim';

export interface AiProviderStatus {
  provider: AiProviderId;
  configured: boolean;
}

/**
 * Serializable projection of an Activity, sent from renderer to main so the
 * system prompt and the semantic validation layer can be built without the
 * main process depending on renderer-only activity state.
 */
export interface AiActivitySnapshot {
  id: string;
  name: string;
  category: string;
  description: string;
  /** Whether this activity returns a value worth capturing into a variable (see AiDiagramNode.outputVariable). */
  hasOutput: boolean;
  outputDescription?: string;
  params: Array<{
    name: string;
    /** ActivityParamType from @rpaforge/activities, kept as a plain string here (main process doesn't depend on that package). */
    type: string;
    required: boolean;
    hasDefault: boolean;
  }>;
}

/**
 * Structural block types the AI may emit. Mirrors BlockType from
 * src/types/blocks.ts minus 'parallel' (generator.ts unconditionally rejects
 * parallel-graph codegen) and 'sub-diagram-call' (requires referencing an
 * existing sub-diagram by id — out of MVP scope, see technical-debt).
 */
export const AI_BLOCK_TYPES = [
  'start',
  'end',
  'if',
  'switch',
  'while',
  'for-each',
  'retry-scope',
  'try-catch',
  'throw',
  'assign',
  'activity',
] as const;

export type AiBlockType = (typeof AI_BLOCK_TYPES)[number];

export interface AiDiagramNode {
  id: string;
  blockType: AiBlockType;
  /** Models sometimes omit this to save tokens; fall back to id/activityId when building the canvas node. */
  label?: string;
  /** Required when blockType === 'activity'; must match an id from the activities snapshot. */
  activityId?: string;
  /** activity: param name -> value, for any params the model wants to configure (others use their defaults). */
  activityParams?: Record<string, string | number | boolean>;
  /** activity: capture this activity's return value into a variable with this name. Only meaningful when the matched activity's hasOutput is true. */
  outputVariable?: string;
  /** if / while */
  condition?: string;
  /** switch */
  expression?: string;
  /** throw */
  message?: string;
  /** assign */
  variableName?: string;
  /** assign */
  variableExpression?: string;
  /** for-each */
  itemVariable?: string;
  /** for-each */
  collection?: string;
  /** switch */
  cases?: Array<{ value: string; label: string }>;
}

export interface AiDiagramEdge {
  from: string;
  to: string;
  /** Port id, e.g. "true"/"false" (if), "case-1"/"default" (switch), "error"/"finally" (try-catch). */
  handle?: string;
}

export interface AiDiagramJson {
  nodes: AiDiagramNode[];
  edges: AiDiagramEdge[];
}

export interface AiGenerateDiagramRequest {
  /** Generated by the renderer (crypto.randomUUID()); lets ai:cancelGenerate abort the matching in-flight request. */
  requestId: string;
  providerId: AiProviderId;
  prompt: string;
  activities: AiActivitySnapshot[];
  language?: string; // User's current UI language (e.g. 'en', 'ru', 'de', 'es', 'zh')
}

export interface TokenUsage {
  prompt: number;
  completion: number;
  total: number;
  costEstimate?: number;
}

export type AiTokenPricing = { model: string; input: number; output: number };

export interface AiGenerateDiagramResult {
  success: boolean;
  diagram?: AiDiagramJson;
  /**
   * Diagnostic-only: raw validator/provider error text. Never render directly
   * in the UI (same i18n rule as mermaidImporter.ts warnings — see ADR-003.2);
   * show a localized generic message instead.
   */
  errors?: string[];
  rawText?: string;
  attempts: number;
  tokenUsage?: TokenUsage;
}

export interface AiSetProviderKeyRequest {
  provider: AiProviderId;
  apiKey: string;
  baseUrl?: string;
  model?: string;
}

export interface AiTestProviderResult {
  ok: boolean;
  error?: string;
}

export interface AiProgressEvent {
  step: 'sending' | 'validating' | 'retry' | 'complete';
  attempt: number;
}

/**
 * Auto-fill parameter values based on process context.
 * Sent from renderer to main process for AI suggestions.
 */
export interface AiAutoFillRequest {
  activityId: string;
  activityName: string;
  activityCategory: string;
  activityParams: Array<{
    name: string;
    type: string;
    required: boolean;
    defaultValue?: string;
  }>;
  variables: Array<{ name: string; type: string; value?: string }>;
  previousActivities: Array<{ name: string; activityId: string; outputs: string[] }>;
}

/**
 * Response from AI provider with suggested parameter values.
 * paramName -> suggested value mapping.
 */
export interface AiAutoFillResult {
  suggestions: Record<string, string>;
}


/**
 * Multi-provider comparison request interface (Issue #600)

 * @see TokenUsage — shared type at line 109
 */
export interface AiCompareRequest {
  requestId: string;
  providers: Array<{
    providerId: AiProviderId;
    prompt: string;
    activities: AiActivitySnapshot[];
    language?: string;
  }>;
}

/**
 * Multi-provider comparison result interface (Issue #600)
 */
export interface AiCompareResult {
  results: Array<{
    providerId: AiProviderId;
    success: boolean;
    diagram?: AiDiagramJson;
    errors?: string[];
    tokenUsage?: TokenUsage;
  }>;
  requestId: string;
}

/**
 * Context for generating activity suggestions.
 * Limited to activity/category IDs only - no raw process data.
 */
export interface SuggestionContext {
  selectedActivityId: string;
  selectedActivityCategory: string;
  processActivities: { id: string; name: string; category: string }[];
  variables: { name: string; type: string }[];
}

/**
 * Suggestion result from AI
 */
export interface SuggestionItem {
  activityId: string;
  label: string;
  reason: string;
}

export interface AiPrompt {
  id: string;
  name: string;
  description: string;
  prompt: string;
  category?: string;
  builtin: boolean;
  createdAt: string;
  updatedAt?: string;
  usageCount?: number;
}

export interface AiPromptLibraryFilters {
  search: string;
  category?: string;
}

export interface AiImportResult {
  success: boolean;
  count: number;
  errors?: string[];
}
